### ISSUE TITLE
multiclasse tracking

### ISSUE THREAD

**Issue by arnaud-nt2i** [viplix3/BoTSORT-cpp#12]
@viplix3 In case of multi class (not only human) should the tracker by shared or we should run on tracker per class ?
( of course CMC can be run once)

**Comment by viplix3** [comment]
@arnaud-nt2i the Kalman Filter algorithm used by the tracker for state estimation encodes various characteristics (change in velocity, aspect ratio changes, etc.) of the object being tracked internally in its mean and covariance state matrices.

So yeah, as you guessed, the tracker should be different for classes having contrasting characteristics to get the best tracking results as you can carefully tune the specific tracker parameters w.r.t. the class characteristics.
For eg. a tracker tuned for vehicles would have higher covariance for velocity compared to a tracker tuned for humans.

That being said, you can, more often than not get away with using the same tracker for multiple classes as well because [the states are being stored in the tracklet](https://github.com/viplix3/BoTSORT-cpp/blob/main/botsort/include/track.h#L29) of each object, and from what I've experience, they tend to work pretty well.

**Take my words with a grain of salt though as I am not an expert in the field.**
